# Generated by Django 5.2.13 on 2026-04-20 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agencies", "0006_remove_old_id_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="division",
            name="approvers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who can approve documents at the directorate stage for this division's business areas.",
                related_name="divisions_approver",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="division",
            name="key_stakeholder",
            field=models.ForeignKey(
                blank=True,
                help_text="The single key stakeholder for this division. Has document approval AND AR admin privileges.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="divisions_key_stakeholder",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
