# Generated by Django 5.2.13 on 2026-05-04 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agencies", "0007_division_approvers_division_key_stakeholder"),
        ("projects", "0017_remove_departmental_service"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DepartmentalService",
        ),
    ]
