# Generated by Django 5.2.13 on 2026-04-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medias", "0010_copy_file_to_draft_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annualreportpdf",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Legacy single-file field, superseded by draft_file and published_file",
                null=True,
                upload_to="annual_reports/pdfs/",
            ),
        ),
    ]
