# Generated by Django 5.2.11 on 2026-03-03 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0002_initial"),
        ("documents", "0010_remove_old_id_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentMention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Comment Mention",
                "verbose_name_plural": "Comment Mentions",
            },
        ),
        migrations.AddField(
            model_name="comment",
            name="parent_comment",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent comment for threaded replies",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="communications.comment",
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["document", "-created_at"],
                name="communicati_documen_8960da_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["user"], name="communicati_user_id_2a7e89_idx"),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["parent_comment"], name="communicati_parent__4396ae_idx"
            ),
        ),
        migrations.AddField(
            model_name="commentmention",
            name="comment",
            field=models.ForeignKey(
                help_text="The comment containing the mention",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mentions",
                to="communications.comment",
            ),
        ),
        migrations.AddField(
            model_name="commentmention",
            name="mentioned_user",
            field=models.ForeignKey(
                help_text="The user who was mentioned",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_mentions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="commentmention",
            index=models.Index(
                fields=["comment"], name="communicati_comment_fba5af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="commentmention",
            index=models.Index(
                fields=["mentioned_user"], name="communicati_mention_142844_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="commentmention",
            unique_together={("comment", "mentioned_user")},
        ),
    ]
