# Generated by Django 5.2.11 on 2026-03-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0003_add_comment_threading_and_mentions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reaction",
            name="reaction",
            field=models.CharField(
                choices=[
                    ("thumbup", "Thumbs Up"),
                    ("heart", "Heart"),
                    ("funny", "Funny"),
                    ("confused", "Confused"),
                    ("surprised", "Surprised"),
                ],
                max_length=30,
            ),
        ),
    ]
