# Generated by Django 5.2.11 on 2026-02-25 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminoptions", "0012_remove_old_id_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admintask",
            name="end_date",
        ),
    ]
