# Generated by Django 5.2.13 on 2026-04-27 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminoptions", "0013_remove_admintask_end_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="adminoptions",
            name="email_test_user",
            field=models.ForeignKey(
                blank=True,
                help_text="Superuser who receives all emails when testing mode is enabled",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="email_test_admin",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="adminoptions",
            name="email_testing_mode",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, all emails are redirected to the designated test user",
            ),
        ),
    ]
