# Generated by Django 5.2.13 on 2026-04-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminoptions", "0014_adminoptions_email_test_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="guidesection",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="guidesection",
            name="icon",
            field=models.CharField(default="book-open", max_length=50),
        ),
    ]
