# Generated by Django 5.2.13 on 2026-04-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminoptions", "0015_add_description_icon_to_guidesection"),
    ]

    operations = [
        migrations.AddField(
            model_name="guidesection",
            name="required_role",
            field=models.CharField(
                choices=[
                    ("all", "All Users"),
                    ("admin", "Admin Only"),
                    ("business_area_lead", "Business Area Lead"),
                    ("key_stakeholder", "Key Stakeholder"),
                ],
                default="all",
                help_text="Minimum role required to view this section",
                max_length=50,
            ),
        ),
    ]
