# Generated by Django 5.2.13 on 2026-05-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminoptions", "0016_add_required_role_to_guidesection"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminoptions",
            name="new_cycle_draft",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Stores the saved new cycle configuration defaults (prepopulate mode, inclusion mode, recipient groups, custom messages)",
            ),
        ),
    ]
