# Generated by Django 5.2.13 on 2026-05-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminoptions", "0017_add_new_cycle_draft"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminoptions",
            name="homepage_message",
            field=models.TextField(
                blank=True,
                help_text="HTML content for the dashboard banner message (from rich text editor)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="adminoptions",
            name="show_homepage_message",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, displays a banner message on the dashboard for all users",
            ),
        ),
    ]
