# Generated by Django 5.2.13 on 2026-05-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0014_remove_old_id_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="status_before_suspend",
            field=models.CharField(
                blank=True,
                choices=[
                    ("new", "New"),
                    ("pending", "Pending Project Plan"),
                    ("active", "Active (Approved)"),
                    ("updating", "Update Requested"),
                    ("closure_requested", "Closure Requested"),
                    ("closing", "Closure Pending Final Update"),
                    ("final_update", "Final Update Requested"),
                    ("completed", "Completed and Closed"),
                    ("terminated", "Terminated and Closed"),
                    ("suspended", "Suspended"),
                ],
                help_text="Stores the project's status before it was suspended, so it can be restored on unsuspension.",
                max_length=50,
                null=True,
            ),
        ),
    ]
