# Generated by Django 5.2.13 on 2026-05-04 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0016_projectdraft"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectdetail",
            name="service",
        ),
    ]
