# Generated by Django 5.2.13 on 2026-05-05 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="branchcontact",
            name="address",
        ),
        migrations.RemoveField(
            model_name="agencycontact",
            name="address",
        ),
        migrations.DeleteModel(
            name="Address",
        ),
    ]
