# Generated by Django 5.2.11 on 2026-02-25 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("caretakers", "0002_copy_data_from_adminoptions"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="caretaker",
            name="caretakers__end_dat_b4d6b9_idx",
        ),
        migrations.RemoveField(
            model_name="caretaker",
            name="end_date",
        ),
    ]
