apiVersion: apps/v1
kind: Deployment
metadata:
  name: spms-deployment
  labels:
    app: spms-prod
spec:
  selector:
    matchLabels:
      app: spms-prod
  template:
    metadata:
      labels:
        app: spms-prod
    spec:
      containers:
        - name: spms-backend
          envFrom:
            - secretRef:
                name: spms-env-prod
          volumeMounts:
            - name: spms-media-blob-prod
              mountPath: /usr/src/app/backend/files
            - name: prince2-license-prod
              mountPath: /usr/lib/prince/license
              readOnly: true
      volumes:
        - name: spms-media-blob-prod
          persistentVolumeClaim:
            claimName: pvc-spms-media-data-blob-prod
        - name: prince2-license-prod
          configMap:
            defaultMode: 420
            name: prince2-license-prod
