# Generated by Django 5.2.13 on 2026-04-20 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agencies", "0007_division_approvers_division_key_stakeholder"),
        ("documents", "0010_remove_old_id_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="annualreport",
            name="division",
            field=models.ForeignKey(
                blank=True,
                help_text="The division this annual report belongs to.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="annual_reports",
                to="agencies.division",
            ),
        ),
    ]
