# Generated by Django 5.2.13 on 2026-04-20 03:54

from django.db import migrations


def set_existing_reports_to_bcs(apps, schema_editor):
    """Set all existing annual reports without a division to BCS."""
    AnnualReport = apps.get_model("documents", "AnnualReport")
    Division = apps.get_model("agencies", "Division")

    try:
        bcs = Division.objects.get(slug="BCS")
        updated = AnnualReport.objects.filter(division__isnull=True).update(
            division=bcs
        )
        if updated:
            print(f"  Set {updated} existing annual report(s) to BCS division")
    except Division.DoesNotExist:
        print("  BCS division not found — skipping backfill")


def reverse_set_reports(apps, schema_editor):
    """Reverse: clear division on all BCS reports."""
    AnnualReport = apps.get_model("documents", "AnnualReport")
    Division = apps.get_model("agencies", "Division")

    try:
        bcs = Division.objects.get(slug="BCS")
        AnnualReport.objects.filter(division=bcs).update(division=None)
    except Division.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0011_annualreport_division"),
        ("agencies", "0007_division_approvers_division_key_stakeholder"),
    ]

    operations = [
        migrations.RunPython(set_existing_reports_to_bcs, reverse_set_reports),
    ]
