# Generated by Django 5.2.13 on 2026-04-20 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0012_set_existing_reports_to_bcs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annualreport",
            name="date_closed",
            field=models.DateField(
                blank=True,
                help_text="The date at which submissions are closed for this report",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="annualreport",
            name="date_open",
            field=models.DateField(
                blank=True,
                help_text="The date at which submissions are opened for this report",
                null=True,
            ),
        ),
    ]
