/**
 * Word Online HTML fixture samples.
 *
 * Real HTML patterns extracted from Microsoft Word Online clipboard output.
 * Used for unit testing the Word HTML → semantic HTML conversion pipeline.
 */

// ─── Inline Formatting ──────────────────────────────────────────────────────

export const ONLINE_BOLD = `<p class="Paragraph"><span data-contrast="auto" xml:lang="EN-GB" lang="EN-GB" class="TextRun MacChromeBold" style="font-size: 12pt; line-height: 27.9px; font-family: WordVisi_MSFontService, Aptos, Aptos_EmbeddedFont, Aptos_MSFontService, sans-serif; font-weight: bold;"><span class="NormalTextRun">Bold text</span></span><span class="EOP"> </span></p>`;

export const ONLINE_ITALIC = `<p class="Paragraph"><span data-contrast="auto" xml:lang="EN-GB" lang="EN-GB" class="TextRun" style="font-size: 12pt; font-style: italic; line-height: 27.9px; font-family: WordVisi_MSFontService, Aptos, Aptos_EmbeddedFont, Aptos_MSFontService, sans-serif;"><span class="NormalTextRun">Italic text</span></span><span class="EOP"> </span></p>`;

export const ONLINE_UNDERLINE = `<p class="Paragraph"><span data-contrast="auto" xml:lang="EN-GB" lang="EN-GB" class="TextRun Underlined" style="font-size: 12pt; text-decoration: underline; line-height: 27.9px; font-family: WordVisi_MSFontService, Aptos, sans-serif;"><span class="NormalTextRun">Underline text</span></span><span class="EOP"> </span></p>`;

export const ONLINE_STRIKETHROUGH = `<p class="Paragraph"><span data-contrast="auto" xml:lang="EN-GB" lang="EN-GB" class="TextRun Strikethrough" style="font-size: 12pt; text-decoration: line-through; line-height: 27.9px; font-family: WordVisi_MSFontService, Aptos, sans-serif;"><span class="NormalTextRun">Strikethrough text</span></span><span class="EOP"> </span></p>`;

export const ONLINE_SUPERSCRIPT = `<p class="Paragraph"><span data-contrast="auto" xml:lang="EN-GB" lang="EN-GB" class="TextRun Superscript" style="font-size: 12pt; vertical-align: super; line-height: 27.9px; font-family: WordVisi_MSFontService, Aptos, sans-serif;"><span class="NormalTextRun">Superscript text</span></span><span class="EOP"> </span></p>`;

export const ONLINE_SUBSCRIPT = `<p class="Paragraph"><span data-contrast="auto" xml:lang="EN-GB" lang="EN-GB" class="TextRun Subscript" style="font-size: 12pt; vertical-align: sub; line-height: 27.9px; font-family: WordVisi_MSFontService, Aptos, sans-serif;"><span class="NormalTextRun">Subscript text</span></span><span class="EOP"> </span></p>`;

// ─── Combination Formatting ─────────────────────────────────────────────────

export const ONLINE_BOLD_ITALIC = `<p class="Paragraph"><span data-contrast="auto" xml:lang="EN-GB" lang="EN-GB" class="TextRun MacChromeBold" style="font-size: 12pt; font-weight: bold; font-style: italic; line-height: 27.9px; font-family: WordVisi_MSFontService, Aptos, sans-serif;"><span class="NormalTextRun">Bold italic text</span></span><span class="EOP"> </span></p>`;

export const ONLINE_BOLD_ITALIC_UNDERLINE = `<p class="Paragraph"><span data-contrast="auto" xml:lang="EN-GB" lang="EN-GB" class="TextRun MacChromeBold Underlined" style="font-size: 12pt; font-weight: bold; font-style: italic; text-decoration: underline; line-height: 27.9px; font-family: WordVisi_MSFontService, Aptos, sans-serif;"><span class="NormalTextRun">Bold italic underline text</span></span><span class="EOP"> </span></p>`;

export const ONLINE_BOLD_STRIKETHROUGH = `<p class="Paragraph"><span data-contrast="auto" xml:lang="EN-GB" lang="EN-GB" class="TextRun MacChromeBold Strikethrough" style="font-size: 12pt; font-weight: bold; text-decoration: line-through; line-height: 27.9px; font-family: WordVisi_MSFontService, Aptos, sans-serif;"><span class="NormalTextRun">Bold strikethrough text</span></span><span class="EOP"> </span></p>`;

// ─── Headings ───────────────────────────────────────────────────────────────

export const ONLINE_HEADING_1 = `<p class="Paragraph" role="heading" aria-level="1"><span data-contrast="none" xml:lang="EN-GB" lang="EN-GB" class="TextRun" style="color: rgb(47, 84, 150); font-size: 20pt; line-height: 43.7px; font-family: WordVisi_MSFontService, Aptos, sans-serif;"><span class="NormalTextRun" data-ccp-parastyle="heading 1">Heading 1 Text</span></span><span class="EOP"> </span></p>`;

export const ONLINE_HEADING_2 = `<p class="Paragraph" role="heading" aria-level="2"><span data-contrast="none" xml:lang="EN-GB" lang="EN-GB" class="TextRun" style="color: rgb(47, 84, 150); font-size: 16pt; line-height: 35.1px; font-family: WordVisi_MSFontService, Aptos, sans-serif;"><span class="NormalTextRun" data-ccp-parastyle="heading 2">Heading 2 Text</span></span><span class="EOP"> </span></p>`;

export const ONLINE_HEADING_3 = `<p class="Paragraph" role="heading" aria-level="3"><span data-contrast="none" xml:lang="EN-GB" lang="EN-GB" class="TextRun" style="color: rgb(47, 84, 150); font-size: 14pt; line-height: 31.2px; font-family: WordVisi_MSFontService, Aptos, sans-serif;"><span class="NormalTextRun" data-ccp-parastyle="heading 3">Heading 3 Text</span></span><span class="EOP"> </span></p>`;

// ─── Unordered Lists ────────────────────────────────────────────────────────

export const ONLINE_UNORDERED_LIST_NESTED = `<li aria-setsize="-1" aria-posinset="1" aria-level="1" role="listitem" class="OutlineElement Ltr"><div class="ParaWrappingDiv"><p class="Paragraph"><span class="ListMarkerWrappingSpan"><span class="ListMarker">•</span></span><span data-contrast="auto" class="TextRun" style="font-size: 12pt;"><span class="NormalTextRun">Level 1 item</span></span><span class="EOP"> </span></p></div></li><li aria-setsize="-1" aria-posinset="1" aria-level="2" role="listitem" class="OutlineElement Ltr"><div class="ParaWrappingDiv"><p class="Paragraph"><span class="ListMarkerWrappingSpan"><span class="ListMarker">o</span></span><span data-contrast="auto" class="TextRun" style="font-size: 12pt;"><span class="NormalTextRun">Level 2 item</span></span><span class="EOP"> </span></p></div></li>`;

// ─── Ordered Lists ──────────────────────────────────────────────────────────

export const ONLINE_ORDERED_LIST_NESTED = `<li aria-setsize="-1" aria-posinset="1" aria-level="1" role="listitem" class="OutlineElement Ltr"><div class="ParaWrappingDiv"><p class="Paragraph"><span class="ListMarkerWrappingSpan"><span class="ListMarker">1.</span></span><span data-contrast="auto" class="TextRun" style="font-size: 12pt;"><span class="NormalTextRun">First item</span></span><span class="EOP"> </span></p></div></li><li aria-setsize="-1" aria-posinset="2" aria-level="1" role="listitem" class="OutlineElement Ltr"><div class="ParaWrappingDiv"><p class="Paragraph"><span class="ListMarkerWrappingSpan"><span class="ListMarker">2.</span></span><span data-contrast="auto" class="TextRun" style="font-size: 12pt;"><span class="NormalTextRun">Second item</span></span><span class="EOP"> </span></p></div></li><li aria-setsize="-1" aria-posinset="1" aria-level="2" role="listitem" class="OutlineElement Ltr"><div class="ParaWrappingDiv"><p class="Paragraph"><span class="ListMarkerWrappingSpan"><span class="ListMarker">a.</span></span><span data-contrast="auto" class="TextRun" style="font-size: 12pt;"><span class="NormalTextRun">Sub item a</span></span><span class="EOP"> </span></p></div></li><li aria-setsize="-1" aria-posinset="1" aria-level="3" role="listitem" class="OutlineElement Ltr"><div class="ParaWrappingDiv"><p class="Paragraph"><span class="ListMarkerWrappingSpan"><span class="ListMarker">i.</span></span><span data-contrast="auto" class="TextRun" style="font-size: 12pt;"><span class="NormalTextRun">Sub sub item i</span></span><span class="EOP"> </span></p></div></li>`;

// ─── Pre-Wrapped Lists (simulates DOMPurify/browser auto-wrapping) ──────────

/**
 * Simulates what happens when DOMPurify processes orphan <li> elements:
 * the browser's DOM parser auto-wraps them in <ul> elements.
 * This is the actual HTML structure that convertWordOnlineLists receives
 * in production (after sanitisation).
 */
export const ONLINE_UNORDERED_LIST_NESTED_WRAPPED = `<ul><li aria-setsize="-1" aria-posinset="1" aria-level="1" role="listitem" class="OutlineElement Ltr"><div class="ParaWrappingDiv"><p class="Paragraph"><span class="ListMarkerWrappingSpan"><span class="ListMarker">•</span></span><span data-contrast="auto" class="TextRun" style="font-size: 12pt;"><span class="NormalTextRun">Level 1 item</span></span><span class="EOP"> </span></p></div></li><li aria-setsize="-1" aria-posinset="1" aria-level="2" role="listitem" class="OutlineElement Ltr"><div class="ParaWrappingDiv"><p class="Paragraph"><span class="ListMarkerWrappingSpan"><span class="ListMarker">o</span></span><span data-contrast="auto" class="TextRun" style="font-size: 12pt;"><span class="NormalTextRun">Level 2 item</span></span><span class="EOP"> </span></p></div></li></ul>`;

export const ONLINE_ORDERED_LIST_NESTED_WRAPPED = `<ul><li aria-setsize="-1" aria-posinset="1" aria-level="1" role="listitem" class="OutlineElement Ltr"><div class="ParaWrappingDiv"><p class="Paragraph"><span class="ListMarkerWrappingSpan"><span class="ListMarker">1.</span></span><span data-contrast="auto" class="TextRun" style="font-size: 12pt;"><span class="NormalTextRun">First item</span></span><span class="EOP"> </span></p></div></li><li aria-setsize="-1" aria-posinset="2" aria-level="1" role="listitem" class="OutlineElement Ltr"><div class="ParaWrappingDiv"><p class="Paragraph"><span class="ListMarkerWrappingSpan"><span class="ListMarker">2.</span></span><span data-contrast="auto" class="TextRun" style="font-size: 12pt;"><span class="NormalTextRun">Second item</span></span><span class="EOP"> </span></p></div></li><li aria-setsize="-1" aria-posinset="1" aria-level="2" role="listitem" class="OutlineElement Ltr"><div class="ParaWrappingDiv"><p class="Paragraph"><span class="ListMarkerWrappingSpan"><span class="ListMarker">a.</span></span><span data-contrast="auto" class="TextRun" style="font-size: 12pt;"><span class="NormalTextRun">Sub item a</span></span><span class="EOP"> </span></p></div></li><li aria-setsize="-1" aria-posinset="1" aria-level="3" role="listitem" class="OutlineElement Ltr"><div class="ParaWrappingDiv"><p class="Paragraph"><span class="ListMarkerWrappingSpan"><span class="ListMarker">i.</span></span><span data-contrast="auto" class="TextRun" style="font-size: 12pt;"><span class="NormalTextRun">Sub sub item i</span></span><span class="EOP"> </span></p></div></li></ul>`;

/**
 * Simulates multiple separate <ul> wrappers (can happen when non-list content
 * separates groups of <li> elements during DOMPurify processing).
 */
export const ONLINE_ORDERED_LIST_MULTIPLE_WRAPPERS = `<ul><li aria-setsize="-1" aria-posinset="1" aria-level="1" role="listitem" class="OutlineElement Ltr"><div class="ParaWrappingDiv"><p class="Paragraph"><span class="ListMarkerWrappingSpan"><span class="ListMarker">1.</span></span><span data-contrast="auto" class="TextRun" style="font-size: 12pt;"><span class="NormalTextRun">First item</span></span><span class="EOP"> </span></p></div></li></ul><ul><li aria-setsize="-1" aria-posinset="2" aria-level="1" role="listitem" class="OutlineElement Ltr"><div class="ParaWrappingDiv"><p class="Paragraph"><span class="ListMarkerWrappingSpan"><span class="ListMarker">2.</span></span><span data-contrast="auto" class="TextRun" style="font-size: 12pt;"><span class="NormalTextRun">Second item</span></span><span class="EOP"> </span></p></div></li></ul>`;

// ─── Junk-Heavy Sample ──────────────────────────────────────────────────────

export const ONLINE_JUNK_HEAVY = `<div class="OutlineElement Ltr"><div class="ParaWrappingDiv"><p class="Paragraph" paraid="123" paraeid="456"><span data-contrast="auto" data-fontsize="12" xml:lang="EN-GB" lang="EN-GB" class="TextRun" style="font-size: 12pt; font-kerning: none; line-height: 27.9px; font-family: WordVisi_MSFontService, Aptos, Aptos_EmbeddedFont, Aptos_MSFontService, sans-serif; color: rgb(0, 0, 0);"><span class="NormalTextRun">Clean content here</span></span><span class="EOP"> </span></p></div></div>`;

// ─── Actual Clipboard HTML (data-aria-level format) ─────────────────────────

/**
 * Actual Word Online clipboard HTML for unordered lists.
 * Uses data-aria-level, data-listid, data-list-defn-props, and data-font.
 * This is what the browser clipboard actually provides (NOT the rendered page HTML).
 */
export const ONLINE_CLIPBOARD_UNORDERED_LIST = `<ul><li aria-setsize="-1" data-leveltext="\uf0b7" data-font="Symbol" data-listid="1" data-list-defn-props='{"335552541":1,"335559683":0,"335559684":-2,"335559685":720,"335559991":360,"469769226":"Symbol","469769242":[8226],"469777803":"left","469777804":"","469777815":"hybridMultilevel"}' data-aria-posinset="1" data-aria-level="1" role="listitem" class="OutlineElement Ltr SCXW140729081 BCX0"><p class="Paragraph"><span data-contrast="auto" class="TextRun" style="font-size: 12pt;"><span class="NormalTextRun">Level 1 bullet</span></span><span class="EOP"> </span></p></li><li aria-setsize="-1" data-leveltext="o" data-font="Courier New" data-listid="1" data-list-defn-props='{"335552541":1,"335559683":0,"335559684":-2,"335559685":1440,"335559991":360,"469769226":"Courier New","469769242":[111],"469777803":"left","469777804":"","469777815":"hybridMultilevel"}' data-aria-posinset="1" data-aria-level="2" role="listitem" class="OutlineElement Ltr SCXW140729081 BCX0"><p class="Paragraph"><span data-contrast="auto" class="TextRun" style="font-size: 12pt;"><span class="NormalTextRun">Level 2 bullet</span></span><span class="EOP"> </span></p></li></ul>`;

/**
 * Actual Word Online clipboard HTML for ordered lists.
 * Uses data-list-defn-props with non-Symbol font to indicate ordered.
 */
export const ONLINE_CLIPBOARD_ORDERED_LIST = `<ul><li aria-setsize="-1" data-leveltext="%1." data-font="Aptos" data-listid="2" data-list-defn-props='{"335552541":0,"335559683":0,"335559684":-2,"335559685":720,"335559991":360,"469769226":"Aptos","469769242":[37,49,46],"469777803":"left","469777804":"%1.","469777815":"hybridMultilevel"}' data-aria-posinset="1" data-aria-level="1" role="listitem" class="OutlineElement Ltr SCXW140729081 BCX0"><p class="Paragraph"><span data-contrast="auto" class="TextRun" style="font-size: 12pt;"><span class="NormalTextRun">First ordered</span></span><span class="EOP"> </span></p></li><li aria-setsize="-1" data-leveltext="%1." data-font="Aptos" data-listid="2" data-list-defn-props='{"335552541":0,"335559683":0,"335559684":-2,"335559685":720,"335559991":360,"469769226":"Aptos","469769242":[37,49,46],"469777803":"left","469777804":"%1.","469777815":"hybridMultilevel"}' data-aria-posinset="2" data-aria-level="1" role="listitem" class="OutlineElement Ltr SCXW140729081 BCX0"><p class="Paragraph"><span data-contrast="auto" class="TextRun" style="font-size: 12pt;"><span class="NormalTextRun">Second ordered</span></span><span class="EOP"> </span></p></li><li aria-setsize="-1" data-leveltext="%1." data-font="Aptos" data-listid="2" data-list-defn-props='{"335552541":0,"335559683":0,"335559684":-2,"335559685":1440,"335559991":360,"469769226":"Aptos","469769242":[37,49,46],"469777803":"left","469777804":"%1.","469777815":"hybridMultilevel"}' data-aria-posinset="1" data-aria-level="2" role="listitem" class="OutlineElement Ltr SCXW140729081 BCX0"><p class="Paragraph"><span data-contrast="auto" class="TextRun" style="font-size: 12pt;"><span class="NormalTextRun">Sub item a</span></span><span class="EOP"> </span></p></li></ul>`;

/**
 * Actual Word Online clipboard HTML for nested ordered list with 3 levels.
 */
export const ONLINE_CLIPBOARD_ORDERED_LIST_3_LEVELS = `<ul><li aria-setsize="-1" data-leveltext="%1." data-font="Aptos" data-listid="3" data-list-defn-props='{"335552541":0,"335559683":0,"335559684":-2,"335559685":720,"335559991":360,"469769226":"Aptos","469769242":[37,49,46],"469777803":"left","469777804":"%1.","469777815":"hybridMultilevel"}' data-aria-posinset="1" data-aria-level="1" role="listitem" class="OutlineElement Ltr SCXW140729081 BCX0"><p class="Paragraph"><span data-contrast="auto" class="TextRun" style="font-size: 12pt;"><span class="NormalTextRun">First item</span></span><span class="EOP"> </span></p></li><li aria-setsize="-1" data-leveltext="%1." data-font="Aptos" data-listid="3" data-list-defn-props='{"335552541":0,"335559683":0,"335559684":-2,"335559685":1440,"335559991":360,"469769226":"Aptos","469769242":[37,49,46],"469777803":"left","469777804":"%1.","469777815":"hybridMultilevel"}' data-aria-posinset="1" data-aria-level="2" role="listitem" class="OutlineElement Ltr SCXW140729081 BCX0"><p class="Paragraph"><span data-contrast="auto" class="TextRun" style="font-size: 12pt;"><span class="NormalTextRun">Sub item a</span></span><span class="EOP"> </span></p></li><li aria-setsize="-1" data-leveltext="%1." data-font="Aptos" data-listid="3" data-list-defn-props='{"335552541":0,"335559683":0,"335559684":-2,"335559685":2160,"335559991":360,"469769226":"Aptos","469769242":[37,49,46],"469777803":"left","469777804":"%1.","469777815":"hybridMultilevel"}' data-aria-posinset="1" data-aria-level="3" role="listitem" class="OutlineElement Ltr SCXW140729081 BCX0"><p class="Paragraph"><span data-contrast="auto" class="TextRun" style="font-size: 12pt;"><span class="NormalTextRun">Sub sub item i</span></span><span class="EOP"> </span></p></li></ul>`;
