name: Docker Image CI for GHCR

on:
  push:
    tags:
      - "*"

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        run: docker login --username idabblewith --password ${{ secrets.GH_PAT }} ghcr.io

      - name: Get the tag name
        id: tag
        run: echo "::set-output name=TAG_NAME::${GITHUB_REF#refs/tags/}"

      - name: Build and Push Image
        env:
            PRODUCTION_BACKEND_BASE_URL: "https://scienceprojects.dbca.gov.au/"
            PRODUCTION_BACKEND_API_URL: "https://scienceprojects.dbca.gov.au/api/v1/"
        run: |
          docker build . --build-arg PRODUCTION_BACKEND_BASE_URL=$PRODUCTION_BACKEND_BASE_URL --build-arg PRODUCTION_BACKEND_API_URL=$PRODUCTION_BACKEND_API_URL  --tag ghcr.io/dbca-wa/science-projects-client:${{ steps.tag.outputs.TAG_NAME }}
          docker push ghcr.io/dbca-wa/science-projects-client:${{ steps.tag.outputs.TAG_NAME }}
          docker tag ghcr.io/dbca-wa/science-projects-client:${{ steps.tag.outputs.TAG_NAME }} ghcr.io/dbca-wa/science-projects-client:latest
          docker push ghcr.io/dbca-wa/science-projects-client:latest

      - name: Build and Push Test Image
        env:
          PRODUCTION_BACKEND_BASE_URL: "https://scienceprojects-test.dbca.gov.au/"
          PRODUCTION_BACKEND_API_URL: "https://scienceprojects-test.dbca.gov.au/api/v1/"
        run: | 
          docker build . --build-arg PRODUCTION_BACKEND_BASE_URL=$PRODUCTION_BACKEND_BASE_URL --build-arg PRODUCTION_BACKEND_API_URL=$PRODUCTION_BACKEND_API_URL --tag ghcr.io/dbca-wa/science-projects-client:test-${{ steps.tag.outputs.TAG_NAME }}
          docker push ghcr.io/dbca-wa/science-projects-client:test-${{ steps.tag.outputs.TAG_NAME }}
          docker tag ghcr.io/dbca-wa/science-projects-client:test-${{ steps.tag.outputs.TAG_NAME }} ghcr.io/dbca-wa/science-projects-client:test
          docker push ghcr.io/dbca-wa/science-projects-client:test
